######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 8 20:26:33 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Plotter.h
SOURCES += main.cpp Plotter.cpp
